[env.dev]
endpoints = ["http://localhost:9200"]
default   = true
index     = "dev-*"
output    = "pretty"

[env.prod]
endpoints = ["http://localhost:9299"]
default   = false
index     = "prod-*"
output    = "pretty"

[env.dd]
endpoints       = ["https://api.datadoghq.eu/"]
default         = false
source          = "datadog"
output          = "pretty"
dd_api_key      = "get one from your DevOps"
dd_personal_key = "get one in your account settings"

[output.pretty]
exclude = ["kubernetes", "message", "@timestamp"]
format = "json"
decode_recursively = true

[output.message]
only = ["message"]
format = "json"

[output.all]
format = "json"

[aliases]
app = "kubernetes.labels.app"
env = "kubernetes.labels.environment"
